# See https://houndci.com/configuration for help.
javascript:
  config_file: .javascript-style.json
  enabled: true
  # ignore_file: .javascript_ignore
ruby:
  enabled: true
scss:
  config_file: .scss-style.yml
