language: ruby
cache: bundler
rvm:
  - 2.2.2
branches:
  only:
    - master
services:
  - postgresql
install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake
before_script:
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/rake db:create db:schema:load
